---
- hosts: all
  become: true
  tasks:
    - name: install apache package
      ansible.builtin.package:
        name: httpd
        state: present

    - name: install support for php
      ansible.builtin.package:
        name: php
        state: present
