---
- name: Installation af web + db
  hosts: all
  become: true

  pre_tasks:
    - name: Install updates for Fedora
      tags: always
      ansible.builtin.dnf:
        update_only: true
        update_cache: true
      when: ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "7"

    - name: Install updates for Ubuntu
      tags: always
      ansible.builtin.apt:
        upgrade: dist
        update_cache: true
      when: ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_major_version'] == "24"

  tasks:
    - name: Install apache on webservers
      tags: apache,ubuntu
      ansible.builtin.apt:
        name:
          - apache2
          - libapache2-mod-php
      when: ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_major_version'] == "24"

    - name: Install mariadb package on db_servers
      tags: db,Fedora
      ansible.builtin.dnf:
        name: mariadb
      when: ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "7"
