---
- name: Installation af web + db med brugeroprettelse og konfiguration
  hosts: all
  become: true

  pre_tasks: 
    - name: Create user 'simone'
      tags: always
      ansible.builtin.user:
        name: simone
        groups: root
        state: present

    - name: Add sudoers file for user 'simone'
      tags: always     
      ansible.builtin.copy:
        src: sudoer_simone
        dest: /etc/sudoers.d/simone
        owner: root
        group: root
        mode: '0440'

    - name: Add SSH key for user 'simone'
      tags: always
      ansible.builtin.authorized_key:
        user: simone
        key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIECcJz4rBgCw2y2ZNuQitBBDretM4wBt0Ku6XcmpIg5p ru1l@kk-sandbox-p01"

- name: Installation på web_servers
  hosts: web_servers
  become: true
  tasks:
    - name: Install Apache on web servers (Ubuntu)
      tags: apache, ubuntu
      ansible.builtin.apt:
        name:
          - apache2
          - libapache2-mod-php
        state: present
      when: ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_major_version'] == "24"

    - name: Install Apache on web servers (RHEL)
      tags: apache, rhel
      ansible.builtin.dnf:
        name: httpd
        state: present
      when: ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "9"

    - name: Ensure Apache is running (Ubuntu)
      tags: apache, ubuntu
      ansible.builtin.service:
        name: apache2
        state: started
      when: ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_major_version'] == "24"

    - name: Ensure Apache is running (RHEL)
      tags: apache, rhel
      ansible.builtin.service:
        name: httpd
        state: started
      when: ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "9"

    - name: Change ServerAdmin email address for Apache (RHEL)
      tags: apache, rhel
      ansible.builtin.replace:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^ServerAdmin\s+.*$'
        replace: 'ServerAdmin somebody@somewhere\.net@example.com'  # Sørg for at bruge en korrekt email-adresse
      when: ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "9"
      register: httpd

    - name: Restart httpd if configuration changed (RHEL)
      tags: apache, rhel
      ansible.builtin.service:
        name: httpd
        state: restarted
      when: httpd.changed

    - name: Copy HTML file for site (Ubuntu)
      tags: apache, ubuntu
      ansible.builtin.copy:
        src: default_site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: '0644'
      when: ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_major_version'] == "24"

    - name: Install MariaDB package on DB servers (RHEL)
      tags: db, rhel
      ansible.builtin.dnf:
        name: mariadb
        state: present
      when: ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "9"
